### ISSUE TITLE
Game Engine: Cubyz is a zig language Voxel Game Engine

### ISSUE THREAD

**Issue by jujubeja** [gmh5225/awesome-game-security#44]
[Cubyz](https://github.com/PixelGuys/Cubyz) - Voxel sandbox game with a large render distance, procedurally generated content and some cool graphical effects.

**Comment by gmh5225** [comment]
Thank you. https://github.com/gmh5225/awesome-game-security/commit/409b1914d76887c2a9bf345327c8eef4b0cf95a8
