### ISSUE TITLE
Malware Is In Your List

### ISSUE THREAD

**Issue by CycloneRing** [gmh5225/awesome-game-security#8]
Hi following project is a scam malware 
https://github.com/gmh5225/Hwid-Spoofer-Valorant-Eac-Be-Vanguard-Permanted-Temporary-Spoofer

the solution file is a binary malware and codes are stitched randomly to make it look legit.

**Comment by gmh5225** [comment]
Thank you. I got it.
Now I have deleted this link https://github.com/gmh5225/awesome-game-security/commit/74506a4f0c8c2895e58a21460fdc08ba0f495bee
